[config]
schemaVersion = "0.0.1"

[package]
namespace = "Maskedcreeper10_RYS"
name = "MetalOST"
versionNumber = "1.0.0"
description = "A mod that aims to replace all of Silksong's original music with hand made metal covers by RYS"
websiteUrl = "https://github.com/maskedcreeper10/SilkMetalOST"
containsNsfwContent = false
[package.dependencies]
silksong_modding-BepInExPack_Silksong = "1.0.3"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "../bin/Debug/netstandard2.1.MetalOST.dll"
target = "/"


[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong"]
[publish.categories]
hollow-knight-silksong = [ "mods", "cosmetic", ]


